### ISSUE TITLE
GraphOne download and trail

### ISSUE THREAD

**Issue by theseusyang** [pradeep-k/GraphOne#1]
Hi Pradeep,

We are a startup company,  develop some graph applications in cloud for customers. this week, we are amazed to find  this project  and read the paper.
Graphone is high-performance graph store engine, maybe fastest by now. Can you send us a copy of codes to test it on our scenarios?

Thank you very much!

theseus yang

theseusyang@hotmail.com

**Comment by pradeep-k** [comment]
Hi Theseus,
The code is open sourced now. I will update the usage guide soon, so that you can test on your scenarios.

**Comment by pradeep-k** [comment]
I have updated the user guide as well. Hope that the user guide will be helpful. I am closing the issue now.

Please raise another issue, if you find any problem.
